"use client";

import Link from "next/link";
import { useState } from "react";
import {
  FileText,
  Shield,
  Lock,
  CheckCircle,
  ChevronDown,
  FileDown,
  Zap,
  Receipt,
  Building2,
  Users,
  TrendingUp,
  FileSpreadsheet,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { cn } from "@/lib/utils";

// ─── Data ────────────────────────────────────────────────────────────────────

const FEATURE_CARDS = [
  {
    icon: Receipt,
    name: "GSTR-3B",
    color: "text-primary",
    bg: "bg-primary/10",
    fields: [
      "GSTIN & Tax Period",
      "Output IGST / CGST / SGST",
      "ITC matrix (IGST / CGST / SGST)",
      "Tax payables & net tax",
      "Financial Year",
      "35 fields total",
    ],
  },
  {
    icon: Users,
    name: "ESIC",
    color: "text-secondary",
    bg: "bg-secondary/10",
    fields: [
      "Employer Code",
      "Employer & Employee contributions",
      "Challan number & date",
      "Number of IPs",
      "Contribution period",
    ],
  },
  {
    icon: Building2,
    name: "PF ECR",
    color: "text-primary",
    bg: "bg-primary/10",
    fields: [
      "Establishment ID & name",
      "AC01 / AC02 / AC10 / AC21 / AC22 breakdowns",
      "Wage month & TRRN",
      "Total members",
      "Admin charges & total",
    ],
  },
  {
    icon: FileText,
    name: "TDS ITNS281",
    color: "text-secondary",
    bg: "bg-secondary/10",
    fields: [
      "TAN & PAN",
      "Tax / Surcharge / Cess / Interest",
      "Section & Major Head",
      "BSR Code & Challan No",
      "Date of deposit",
      "16 fields total",
    ],
  },
  {
    icon: FileSpreadsheet,
    name: "PTRC",
    color: "text-primary",
    bg: "bg-primary/10",
    fields: [
      "Maharashtra PT (PTRC No)",
      "TAN of employer",
      "PT paid & challan no",
      "Period & employee count",
    ],
  },
];

const PLANS = [
  {
    key: "free",
    name: "Free",
    price: "₹0",
    period: "forever",
    limit: "2 PDFs / month",
    pdfCount: "2 PDFs",
    features: [
      "2 PDFs per month",
      "All 5 document types",
      "Excel export",
      "Email support",
    ],
    cta: "Get Started Free",
    featured: false,
    navy: false,
  },
  {
    key: "starter",
    name: "Starter",
    price: "₹249",
    period: "/ month",
    limit: "25 PDFs / month",
    pdfCount: "25 PDFs",
    features: [
      "25 PDFs per month",
      "All 5 document types",
      "Excel + Google Sheets export",
      "Email support",
    ],
    cta: "Start Starter",
    featured: false,
    navy: false,
  },
  {
    key: "standard",
    name: "Standard",
    price: "₹449",
    period: "/ month",
    limit: "50 PDFs / month",
    pdfCount: "50 PDFs",
    features: [
      "50 PDFs per month",
      "All 5 document types",
      "Excel + Google Sheets export",
      "Priority support",
    ],
    cta: "Start Standard",
    featured: true,
    navy: false,
    badge: "Most Popular",
  },
  {
    key: "pro",
    name: "Pro",
    price: "₹699",
    period: "/ month",
    limit: "120 PDFs / month",
    pdfCount: "120 PDFs",
    features: [
      "120 PDFs per month",
      "All 5 document types",
      "Excel + Google Sheets export",
      "Priority support",
      "Dedicated account manager",
    ],
    cta: "Start Pro",
    featured: false,
    navy: true,
  },
];

const FAQS = [
  {
    q: "Is my data secure?",
    a: "Yes. StatutorySync is DPDP-compliant and processes your PDFs entirely in-memory. Files are never stored on our servers — only metadata (file hash, doc type, timestamp) is retained for usage tracking. Your financial data is discarded immediately after parsing.",
  },
  {
    q: "Which PDF formats are supported?",
    a: "We support text-based PDFs generated by official government portals (GSTN, EPFO, ESIC, Income Tax). Scanned or image-based PDFs are not supported in V1 — OCR support is on our roadmap.",
  },
  {
    q: "What does 'PDFs/month' mean?",
    a: "Each PDF file you upload and parse counts as one unit toward your monthly allowance. The counter resets on the 1st of each calendar month. Unused PDFs do not roll over.",
  },
];

// ─── Sub-components ───────────────────────────────────────────────────────────

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-border rounded-lg overflow-hidden bg-white">
      <button
        className="w-full flex items-center justify-between px-6 py-4 text-left font-medium text-foreground hover:bg-muted transition-colors"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
      >
        <span>{q}</span>
        <ChevronDown
          className={cn(
            "h-4 w-4 text-muted-foreground transition-transform duration-200 flex-shrink-0 ml-4",
            open && "rotate-180"
          )}
        />
      </button>
      {open && (
        <div className="px-6 py-4 text-muted-foreground text-sm border-t border-border leading-relaxed">
          {a}
        </div>
      )}
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background font-sans">
      {/* ── Sticky Nav ─────────────────────────────────────────────────────── */}
      <nav className="sticky top-0 z-50 bg-white/90 backdrop-blur-sm border-b border-border shadow-sm transition-all">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-primary rounded-md flex items-center justify-center">
              <FileText className="h-4 w-4 text-white" />
            </div>
            <span className="font-bold text-xl text-primary tracking-tight">StatutorySync</span>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/login">
              <Button variant="ghost" size="sm" className="text-primary hover:text-primary">
                Login
              </Button>
            </Link>
            <Link href="/signup">
              <Button
                size="sm"
                className="bg-accent hover:bg-accent/90 text-accent-foreground font-semibold"
              >
                Get Started Free
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* ── Hero ───────────────────────────────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-20 text-center">
        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-primary leading-tight mb-5 tracking-tight">
          Automate Statutory Dues<br />
          <span className="text-secondary">Compliance</span>
        </h1>
        <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto mb-10">
          Upload PDFs. Get structured data. In seconds.
        </p>

        <Link href="/signup">
          <Button
            size="lg"
            className="bg-accent hover:bg-accent/90 text-accent-foreground font-semibold px-10 py-3 text-base h-auto shadow-md"
          >
            Start Free — 2 PDFs included
          </Button>
        </Link>

        {/* Social proof numbers */}
        <div className="mt-8 flex flex-wrap items-center justify-center gap-8">
          {[
            { number: "500+", label: "CAs using StatutorySync" },
            { number: "5", label: "Document types supported" },
            { number: "0 bytes", label: "Client data stored on servers" },
          ].map(({ number, label }) => (
            <div key={label} className="text-center">
              <div className="text-2xl font-bold text-primary tabular-nums">{number}</div>
              <div className="text-xs text-muted-foreground mt-0.5">{label}</div>
            </div>
          ))}
        </div>

        {/* Trust pills */}
        <div className="mt-10 flex flex-wrap items-center justify-center gap-3">
          {[
            { icon: Shield, label: "DPDP Compliant" },
            { icon: Lock, label: "Files Never Stored" },
            { icon: FileText, label: "5 Doc Types" },
            { icon: CheckCircle, label: "Excel & Google Sheets output" },
          ].map(({ icon: Icon, label }) => (
            <div
              key={label}
              className="flex items-center gap-2 px-4 py-2 bg-white border border-border rounded-full text-sm text-muted-foreground shadow-sm"
            >
              <Icon className="h-4 w-4 text-secondary flex-shrink-0" />
              {label}
            </div>
          ))}
        </div>
      </section>

      {/* ── Feature Cards ──────────────────────────────────────────────────── */}
      <section className="bg-white py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-primary mb-3 tracking-tight">
            Every Document Type Covered
          </h2>
          <p className="text-center text-muted-foreground mb-12 max-w-xl mx-auto">
            Purpose-built parsers for each statutory document — no generic OCR guesswork.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURE_CARDS.map((card) => {
              const Icon = card.icon;
              return (
                <Card key={card.name} className="hover:shadow-lg hover:-translate-y-0.5 transition-all duration-200">
                  <CardHeader className="pb-3">
                    <div className="flex items-center gap-3">
                      <div
                        className={cn(
                          "w-10 h-10 rounded-lg flex items-center justify-center",
                          card.bg
                        )}
                      >
                        <Icon className={cn("h-5 w-5", card.color)} />
                      </div>
                      <h3 className="text-lg font-semibold text-primary">{card.name}</h3>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-1.5">
                      {card.fields.map((field) => (
                        <li key={field} className="flex items-start gap-2 text-sm">
                          <CheckCircle className="h-3.5 w-3.5 text-secondary mt-0.5 flex-shrink-0" />
                          <span className="text-muted-foreground">{field}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              );
            })}
            {/* Google Sheets card */}
            <Card className="bg-secondary/5 border-secondary/20 hover:shadow-lg hover:-translate-y-0.5 transition-all duration-200">
              <CardHeader className="pb-3">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-secondary/10 flex items-center justify-center">
                    <Zap className="h-5 w-5 text-secondary" />
                  </div>
                  <h3 className="text-lg font-semibold text-secondary">One-Click Export</h3>
                </div>
              </CardHeader>
              <CardContent>
                <ul className="space-y-1.5">
                  {[
                    "Download formatted Excel (.xlsx)",
                    "Push to Google Sheets instantly",
                    "Auto-sized columns & styled headers",
                    "Ready to paste into master register",
                  ].map((f) => (
                    <li key={f} className="flex items-start gap-2 text-sm">
                      <CheckCircle className="h-3.5 w-3.5 text-secondary mt-0.5 flex-shrink-0" />
                      <span className="text-muted-foreground">{f}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* ── How it works ───────────────────────────────────────────────────── */}
      <section className="py-20 bg-background">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-primary mb-12 tracking-tight">
            How It Works
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            {[
              {
                step: "01",
                title: "Upload PDFs",
                desc: "Drag and drop up to 20 statutory PDFs at once. All 5 document types supported.",
                icon: FileText,
              },
              {
                step: "02",
                title: "Instant Parsing",
                desc: "Our purpose-built engine extracts all key fields in under 3 seconds per file.",
                icon: Zap,
              },
              {
                step: "03",
                title: "Export & Use",
                desc: "Download Excel or push directly to Google Sheets — ready for your master register.",
                icon: TrendingUp,
              },
            ].map(({ step, title, desc, icon: Icon }) => (
              <div key={step} className="flex flex-col items-center text-center">
                <div className="w-16 h-16 bg-primary rounded-2xl flex items-center justify-center text-white mb-4 shadow-md">
                  <Icon className="h-7 w-7" />
                </div>
                <span className="text-xs font-bold text-muted-foreground tracking-widest mb-2">
                  STEP {step}
                </span>
                <h3 className="text-lg font-semibold text-primary mb-2">{title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pricing ────────────────────────────────────────────────────────── */}
      <section className="bg-white py-20" id="pricing">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-primary mb-3 tracking-tight">
            Simple, Transparent Pricing
          </h2>
          <p className="text-center text-muted-foreground mb-12">
            Start free. Upgrade when you need more.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 items-start">
            {PLANS.map((plan) => (
              <div
                key={plan.key}
                className={cn(
                  "rounded-xl border p-6 flex flex-col relative",
                  plan.navy
                    ? "bg-primary border-primary text-white shadow-xl"
                    : plan.featured
                    ? "border-accent shadow-lg ring-2 ring-accent/30"
                    : "bg-white border-border"
                )}
              >
                {plan.badge && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                    <span className="bg-accent text-accent-foreground text-xs font-bold px-3 py-1 rounded-full whitespace-nowrap">
                      {plan.badge}
                    </span>
                  </div>
                )}

                <div className="mb-5 mt-1">
                  <h3
                    className={cn(
                      "text-lg font-bold mb-1",
                      plan.navy ? "text-white" : "text-primary"
                    )}
                  >
                    {plan.name}
                  </h3>
                  <div className="flex items-baseline gap-1">
                    <span
                      className={cn(
                        "text-3xl font-bold",
                        plan.navy ? "text-white" : "text-foreground"
                      )}
                    >
                      {plan.price}
                    </span>
                    <span
                      className={cn(
                        "text-sm",
                        plan.navy ? "text-white/70" : "text-muted-foreground"
                      )}
                    >
                      {plan.period}
                    </span>
                  </div>
                  <p
                    className={cn(
                      "text-sm font-semibold mt-1",
                      plan.navy ? "text-accent" : "text-secondary"
                    )}
                  >
                    {plan.pdfCount} / month
                  </p>
                </div>

                <ul className="space-y-2.5 flex-1 mb-6">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-start gap-2 text-sm">
                      <CheckCircle
                        className={cn(
                          "h-4 w-4 mt-0.5 flex-shrink-0",
                          plan.navy ? "text-accent" : "text-secondary"
                        )}
                      />
                      <span
                        className={cn(
                          plan.navy ? "text-white/90" : "text-muted-foreground"
                        )}
                      >
                        {f}
                      </span>
                    </li>
                  ))}
                </ul>

                <Link href="/signup">
                  <Button
                    className={cn(
                      "w-full font-semibold",
                      plan.navy
                        ? "bg-accent hover:bg-accent/90 text-accent-foreground"
                        : plan.featured
                        ? "bg-primary hover:bg-primary/90 text-white"
                        : ""
                    )}
                    variant={plan.navy || plan.featured ? "default" : "outline"}
                  >
                    {plan.cta}
                  </Button>
                </Link>
              </div>
            ))}
          </div>

          {/* All plans include */}
          <div className="mt-10 border border-border rounded-xl bg-muted/40 px-6 py-4 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm text-muted-foreground">
            <span className="font-semibold text-foreground">All plans include:</span>
            {["All 5 document types", "Excel download", "DPDP compliant", "No data stored", "Email support"].map((f) => (
              <span key={f} className="flex items-center gap-1.5">
                <CheckCircle className="h-3.5 w-3.5 text-secondary" />
                {f}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ────────────────────────────────────────────────────────────── */}
      <section className="py-20 bg-background">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-primary mb-12 tracking-tight">
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            {FAQS.map((faq) => (
              <FAQItem key={faq.q} q={faq.q} a={faq.a} />
            ))}
          </div>
        </div>
      </section>

      {/* ── Footer ─────────────────────────────────────────────────────────── */}
      <footer className="bg-primary text-white py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 bg-white/20 rounded flex items-center justify-center">
              <FileText className="h-3 w-3 text-white" />
            </div>
            <span className="font-bold tracking-tight">StatutorySync</span>
          </div>
          <p className="text-white/70 text-sm">
            &copy; 2025 StatutorySync by CA Ujwal Baheti
          </p>
          <div className="flex gap-4 text-sm text-white/70">
            <Link href="/privacy" className="hover:text-white transition-colors">
              Privacy
            </Link>
            <Link href="/terms" className="hover:text-white transition-colors">
              Terms
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
